#!/usr/bin/env python3
"""Generate app/js/data.js (star catalog + constellation lines) from d3-celestial data.

The app ships a compact, pre-generated catalog so it never fetches anything at
runtime. To regenerate:

    curl -O https://registry.npmjs.org/d3-celestial/-/d3-celestial-0.7.35.tgz
    tar -xzf d3-celestial-0.7.35.tgz \
        package/data/stars.6.json package/data/starnames.json \
        package/data/constellations.json package/data/constellations.lines.json
    python3 tools/generate_data.py package/data

d3-celestial is (c) Olaf Frohn, BSD-3-Clause, https://github.com/ofrohn/d3-celestial
Its star data derives from the HYG database (Yale BSC + Hipparcos).
"""
import json
import sys
from pathlib import Path

MAG_LIMIT = 5.0        # stars fainter than this are invisible from most campsites
NAME_MAG_LIMIT = 2.0   # only the brightest stars get an on-map label

def norm_ra(ra):
    """d3-celestial stores RA as -180..180 degrees; normalize to 0..360."""
    return ra % 360.0


def main(data_dir):
    d = Path(data_dir)
    stars = json.loads((d / "stars.6.json").read_text())
    names = json.loads((d / "starnames.json").read_text())
    con_meta = json.loads((d / "constellations.json").read_text())
    con_lines = json.loads((d / "constellations.lines.json").read_text())

    out_stars = []
    for f in stars["features"]:
        mag = f["properties"]["mag"]
        if mag > MAG_LIMIT:
            continue
        ra, dec = f["geometry"]["coordinates"]
        name = ""
        if mag <= NAME_MAG_LIMIT:
            info = names.get(str(f["id"]), {})
            name = info.get("name", "")
        row = [round(norm_ra(ra), 2), round(dec, 2), round(mag, 1)]
        if name:
            row.append(name)
        out_stars.append(row)
    out_stars.sort(key=lambda r: r[2])  # brightest first: draw order + early-exit

    labels = {f["id"]: f for f in con_meta["features"]}
    out_cons = []
    for f in con_lines["features"]:
        cid = f["id"]
        meta = labels.get(cid)
        lines = [
            [[round(norm_ra(p[0]), 2), round(p[1], 2)] for p in seg]
            for seg in f["geometry"]["coordinates"]
        ]
        lp = meta["geometry"]["coordinates"] if meta else lines[0][0]
        out_cons.append({
            "id": cid,
            "name": meta["properties"]["en"] if meta else cid,
            "rank": int(f["properties"].get("rank", 3)),
            "label": [round(norm_ra(lp[0]), 2), round(lp[1], 2)],
            "lines": lines,
        })

    js = (
        "// GENERATED by tools/generate_data.py — do not edit by hand.\n"
        "// Star and constellation data from d3-celestial (BSD-3-Clause, (c) Olaf Frohn),\n"
        "// derived from the HYG database (Yale Bright Star Catalog + Hipparcos).\n"
        "// Format: STARS rows are [raDeg, decDeg, mag] or [raDeg, decDeg, mag, name],\n"
        "// sorted brightest-first. CONSTELLATIONS lines are [raDeg, decDeg] polylines.\n"
        f"export const STARS = {json.dumps(out_stars, separators=(',', ':'))};\n"
        f"export const CONSTELLATIONS = {json.dumps(out_cons, separators=(',', ':'))};\n"
    )
    out = Path(__file__).resolve().parent.parent / "app" / "js" / "data.js"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(js)
    print(f"wrote {out} ({len(js) // 1024} KB): {len(out_stars)} stars, "
          f"{len(out_cons)} constellations")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "package/data")
